### ISSUE TITLE
rasterio.errors.CRSError: The PROJ4 dict could not be understood. OGR Error code 5

### ISSUE THREAD

**Issue by dythbj** [tmnnrs/terrain-rgb#3]
![image](https://user-images.githubusercontent.com/41282663/101864344-0a1e3700-3baf-11eb-92b3-e8c130a6f239.png)
 Mac os X 10.15.7

Any ideas about this error?

**Comment by ajchellew** [comment]
I know this is old but I've had the same fight on both Windows and Ubuntu (when I assumed Windows was the issue). 

If I used rgbify to output to a tif it worked, but if I tried to output to mbtiles it reported OGR Error code 5, on a different version the error was not quite the same but the fix was.

Found https://github.com/mapbox/rasterio/issues/1648 

which lead to my fix:
clone/download rio-rgbify
replace all the 'epsg' strings in mbtiler.py with 'EPSG'
install the modified version
```
cd rio-rgbify
pip install -e '.[test]'
```
omit the single quotes if installing on Windows

**Comment by tmnnrs** [comment]
I also found that the following worked on Ubuntu...

https://github.com/mapbox/rio-rgbify/issues/14

```
git clone -b sgillies-patch-1 https://github.com/mapbox/rio-rgbify.git
cd rio-rgbify
pip install -e '.[test]'
```
